### PR TITLE
Replace RPi.GPIO with rpi-lgpio for V2 legacy

### LINKED ISSUE #2313: 🐛 | bookworm/kernel 6.6 GPIO: Failed to add edge detection
### Version

3.5.2

### Branch

future/main

### OS

RPI OS bookworm lite - 32bit

### Pi model

3 B+

### Hardware

- [Suptronics x400](http://www.suptronics.com/xseries/x400.html) Soundcard
- [MFRC522 RFID Reader](https://rpi-jukebox-rfid.readthedocs.io/en/latest/rfid/mfrc522_spi.html)
- GPIO buttons

### What happened?

After a fresh install of RPI OS bookworm lite, 32-bit with latest `future/main`, the GPIO buttons and the RFID reader stopped working (They worked before with the same configuration on an older 2.x installation on RPI OS bullseye).
I saw [this discussion thread](https://github.com/MiczFlor/RPi-Jukebox-RFID/discussions/2295) which confirms this issue, but I wanted to create a dedicated issue for it, to not bloat the discussion topic too much since it covers also other issues of a bookworm/future/main installation. 

I can see this relevant log entry:

```
Exception in thread read_00Thread:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/varac/RPi-Jukebox-RFID/src/jukebox/components/rfid/reader/__init__.py", line 143, in run
    self._reader = self._reader_module.ReaderClass(self._reader_cfg_key)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/varac/RPi-Jukebox-RFID/src/jukebox/components/rfid/hardware/rc522_spi/rc522_spi.py", line 85, in __init__
    self.device = pirc522.RFID(bus=spi_bus,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/varac/RPi-Jukebox-RFID/.venv/lib/python3.11/site-packages/pirc522/rfid.py", line 103, in __init__
    GPIO.add_event_detect(pin_irq, GPIO.FALLING,
RuntimeError: Failed to add edge detection
```

In the discussion [Sharing tips for future3 on bookworm/kernel 6.6 and upstreaming fixes #2295](https://github.com/MiczFlor/RPi-Jukebox-RFID/discussions/2295) @hoffie pointed out possible ways forward but I am missing concrete instructions know how to actually fix this issue on my current installation. Any help welcome, thanks already !

### Logs

[app.log](https://github.com/MiczFlor/RPi-Jukebox-RFID/files/14812716/app.log)
[errors.log](https://github.com/MiczFlor/RPi-Jukebox-RFID/files/14812717/errors.log)
[INSTALL-1710188086.log](https://github.com/MiczFlor/RPi-Jukebox-RFID/files/14812718/INSTALL-1710188086.log)

### Configuration

[rfid.yaml.txt](https://github.com/MiczFlor/RPi-Jukebox-RFID/files/14812730/rfid.yaml.txt)
[jukebox.yaml.txt](https://github.com/MiczFlor/RPi-Jukebox-RFID/files/14812731/jukebox.yaml.txt)
[gpio.yaml.txt](https://github.com/MiczFlor/RPi-Jukebox-RFID/files/14812733/gpio.yaml.txt)

### More info

_No response_

### LINKED ISSUE #2488: 🐛 | phoniebox-gpio-control.service: Failed with result 'exit-code'
### Version

2.8.0 - 5044358f - master

### Branch

master

### OS

Raspbian GNU/Linux 12 (bookworm)

### Pi model

3 B+

### Hardware

On off shim
Hifi Berry MiniAmp
GPIO extension

### What happened?

Hi

I tried to configure the Buttons using the gpio_settings.ini. When I restart the service i get an error in the journalctl and the script crashes. 

```
Feb 01 08:12:56 phonie systemd[1]: phoniebox-gpio-control.service: Scheduled restart job, restart counter is at 426.
Feb 01 08:12:56 phonie systemd[1]: Stopped phoniebox-gpio-control.service - Phoniebox GPIO Control Service.
Feb 01 08:12:56 phonie systemd[1]: Started phoniebox-gpio-control.service - Phoniebox GPIO Control Service.
Feb 01 08:12:57 phonie PhonieboxGPIOControl[22622]: INFO:__main__:GPIO Started
Feb 01 08:12:57 phonie PhonieboxGPIOControl[22622]: INFO:__main__:['VolumeControl', 'RotaryVolumeControl', 'PrevNextControl', 'PlayPause', 'Shutdown', 'PauseShutdown', 'Volume0', 'VolumeUp', 'VolumeDown'>
Feb 01 08:12:57 phonie PhonieboxGPIOControl[22622]: INFO:__main__:Device VolumeControl not enabled
Feb 01 08:12:57 phonie PhonieboxGPIOControl[22622]: INFO:__main__:Device RotaryVolumeControl not enabled
Feb 01 08:12:57 phonie PhonieboxGPIOControl[22622]: INFO:__main__:Device PrevNextControl not enabled
Feb 01 08:12:57 phonie PhonieboxGPIOControl[22622]: INFO:__main__:adding GPIO-Device, PlayPause
Feb 01 08:12:57 phonie PhonieboxGPIOControl[22622]: PlayPause
Feb 01 08:12:57 phonie PhonieboxGPIOControl[22622]: Traceback (most recent call last):
Feb 01 08:12:57 phonie PhonieboxGPIOControl[22622]:   File "/home/pi/RPi-Jukebox-RFID/components/gpio_control/gpio_control.py", line 140, in <module>
Feb 01 08:12:57 phonie PhonieboxGPIOControl[22622]:     devices = gpio_control_class.get_all_devices(config)
Feb 01 08:12:57 phonie PhonieboxGPIOControl[22622]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 01 08:12:57 phonie PhonieboxGPIOControl[22622]:   File "/home/pi/RPi-Jukebox-RFID/components/gpio_control/gpio_control.py", line 108, in get_all_devices
Feb 01 08:12:57 phonie PhonieboxGPIOControl[22622]:     device = self.generate_device(config[section], section)
Feb 01 08:12:57 phonie PhonieboxGPIOControl[22622]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 01 08:12:57 phonie PhonieboxGPIOControl[22622]:   File "/home/pi/RPi-Jukebox-RFID/components/gpio_control/gpio_control.py", line 62, in generate_device
Feb 01 08:12:57 phonie PhonieboxGPIOControl[22622]:     return SimpleButton(config.getint('Pin'),
Feb 01 08:12:57 phonie PhonieboxGPIOControl[22622]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 01 08:12:57 phonie PhonieboxGPIOControl[22622]:   File "/home/pi/RPi-Jukebox-RFID/components/gpio_control/GPIODevices/simple_button.py", line 93, in __init__
Feb 01 08:12:57 phonie PhonieboxGPIOControl[22622]:     GPIO.add_event_detect(self.pin, edge=self.edge, callback=self.callbackFunctionHandler,
Feb 01 08:12:57 phonie PhonieboxGPIOControl[22622]: RuntimeError: Failed to add edge detection
Feb 01 08:12:57 phonie kernel: export_store: invalid GPIO 11
Feb 01 08:12:57 phonie systemd[1]: phoniebox-gpio-control.service: Main process exited, code=exited, status=1/FAILURE
Feb 01 08:12:57 phonie systemd[1]: phoniebox-gpio-control.service: Failed with result 'exit-code'.
```

I#m wondering if this has to do something with the new GPIO libraries and this bug: [https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2469](url)

### Logs

_No response_

### Configuration

_No response_

### More info

_No response_

### PR DESCRIPTION
**Pull request by s-martin**
Following the discussion in #2313 replacing RPi.GPIO with [rpi-lgpio](https://rpi-lgpio.readthedocs.io/en/latest/index.html)

@hoffie @varac

### CODE REVIEW

**Review by Groovylein — APPROVED** [review]

**Comment by Groovylein** [comment]
I had similar issues and did the same thing. Now everything is working 👍

File: scripts/installscripts/install-jukebox.sh [hunk 1]
```diff
@@ -948,6 +948,9 @@ install_main() {
     echo "${VERSION_NO} - ${COMMIT_NO} - ${USED_BRANCH}" > ${jukebox_dir}/settings/version
     chmod 777 ${jukebox_dir}/settings/version
 
+    # Remove RPi.GPIO, if still installed - see https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/2313
+    sudo python3 -m pip uninstall rpi-gpio
```
Comment (AlvinSchiller) [inline scripts/installscripts/install-jukebox.sh]: if the package is already installed, a confirmation of the user is requested. Option `-y` is needed. Also add quite mode `-q`.
```suggestion
    sudo python3 -m pip uninstall -y -q rpi-gpio
```

**Review by AlvinSchiller — CHANGES_REQUESTED** [review]
This change is not sufficient. If the `pi-rc522` package is installed later on, the dependency for `RPi.GPIO` is resolved and installed. In the end both libs are installed (`rpi-lgpio` and `rpi-gpio`) which breaks the reader.

Possible solution:
On installation of the `pi-rc522` package the option "--no-deps" needs to be added, to not install the `RPi.GPIO` package.

.../components/rfid-reader/RC522/requirements.txt
```
# RC522 related requirements
# You need to install these with `sudo python3 -m pip install --upgrade --force-reinstall --no-deps -q -r requirements.txt`

spidev
pi-rc522==2.3.0
```
.../components/rfid-reader/RC522/setup_rc522.sh#L26
```
sudo python3 -m pip install --upgrade --force-reinstall --no-deps -q -r "${JUKEBOX_HOME_DIR}"/components/rfid-reader/RC522/requirements.txt
```


Downside: if any other package is installed, which has a `RPi.GPIO` dependecy, the reader breaks again. But i did not find any option to block a single package in pip.
Also if the `rpi-lgpio` package would not be installed before, the reader is also non-functional (but as it is listed in our main reqiurement, this is negligible).


Any other/better ideas?

**Comment by AlvinSchiller** [comment]
> This change is not sufficient. If the `pi-rc522` package is installed later on, the dependency for `RPi.GPIO` is resolved and installed. In the end both libs are installed (`rpi-lgpio` and `rpi-gpio`) which breaks the reader.
> 
> Possible solution: On installation of the `pi-rc522` package the option "--no-deps" needs to be added, to not install the `RPi.GPIO` package.
> 
> .../components/rfid-reader/RC522/requirements.txt
> 
> ```
> # RC522 related requirements
> # You need to install these with `sudo python3 -m pip install --upgrade --force-reinstall --no-deps -q -r requirements.txt`
> 
> spidev
> pi-rc522==2.3.0
> ```
> 
> .../components/rfid-reader/RC522/setup_rc522.sh#L26
> 
> ```
> sudo python3 -m pip install --upgrade --force-reinstall --no-deps -q -r "${JUKEBOX_HOME_DIR}"/components/rfid-reader/RC522/requirements.txt
> ```
> 
> Downside: if any other package is installed, which has a `RPi.GPIO` dependecy, the reader breaks again. But i did not find any option to block a single package in pip. Also if the `rpi-lgpio` package would not be installed before, the reader is also non-functional (but as it is listed in our main reqiurement, this is negligible).
> 
> Any other/better ideas?

Another option would be to use the [pi-rc522-gpiozero](https://github.com/hoffie/pi-rc522-gpiozero) from @hoffie. But i did not test it yet.
But this is maybe a too big change for V2. Especially as`gpiozero` is [discouraged](https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/develop/CONTRIBUTING.md#guidelines) in V2.

**Comment by s-martin** [comment]
> This change is not sufficient. If the `pi-rc522` package is installed later on, the dependency for `RPi.GPIO` is resolved and installed. In the end both libs are installed (`rpi-lgpio` and `rpi-gpio`) which breaks the reader.

Good catch!

[…]

> Downside: if any other package is installed, which has a `RPi.GPIO` dependecy, the reader breaks again. But i did not find any option to block a single package in pip. Also if the `rpi-lgpio` package would not be installed before, the reader is also non-functional (but as it is listed in our main reqiurement, this is negligible).
> 
> Any other/better ideas?

For me the downside would be ok as we don’t want to add new functionality to V2 (= no new packages) - nevertheless I’m aware so far we updated many things on V2 although we didn’t want to.

maybe we can add a test to CI, which at least recognizes, if we install RPi.GPIO again.

**Comment by AlvinSchiller** [comment]
Turns out there are some more problems, regarding compatibility to bullseye. 
The `rpi-lgpio` lib throws errors as it seems the binary of `lgpio` is broken fit bullseye (`glibc` is expected in version 2.33 but bullseye only has 2.31).
It works though if `lgpio` is build manually.

I also tried to keep `RPi.GPIO` for bullseye, but that was complicated to handle, especially for automatic tests.

Also the order of de-/installation of the two libs is important. It must be a deinstallation first, otherwise imports are broken
(I tried to play around the" no-deps" option, but this was the showstopper for this solution).


What seems to work now (final tests pending, but ci looks good. Commit with the changes will follow):
- On setup(or update) the old `rpi-gpio` lib is removed (pip and apt as bullseye has the apt package installed by default and pip can't remove it).
- install `rpi-lgpio` as replacement
- manually handle libs with dependencies to `RPi.GPIO` (currently only `pi-rc22`) with the "no-deps" option.
- for bullseye and below manually build `lgpio` 

- check in ci tests that `RPi.GPIO` is not installed.

**Comment by AlvinSchiller** [comment]
Also to mention are some incompatibilities of the libs. See [rpi-lgpio differences](https://rpi-lgpio.readthedocs.io/en/latest/differences.html)

- [Pi 1 Models](https://rpi-lgpio.readthedocs.io/en/latest/differences.html#pi-revision) (B, A, A+, B+, and Compute Module 1) are not supported right away, and need a special environment variable to work. I think this is not a big issue but needs to be documented. 

- The [gpio_function](https://rpi-lgpio.readthedocs.io/en/latest/differences.html#alternate-pin-modes) function behave differently, but I didn't find any usage of it in the project. 

- [simultaneous access](https://rpi-lgpio.readthedocs.io/en/latest/differences.html#simultaneous-access) of pins does not work anymore. Should not be a problem for the main functionality but some special use case with hardware might not work. 

- [debounce](https://rpi-lgpio.readthedocs.io/en/latest/differences.html#debounce) behaviour has changed, which causes some unexpected delay.
This is notable on using Buttons. An example is pressing a button continuously quite fast (debounce == bouncetime defaults to 500ms). 
-- With the old `RPi.GPIO` lib the function is trigger immediatly on press every 500 ms.
-- With the new `rpi-lgpio` lib the function is not triggered at all, only after the state is stable for 500ms (= button not pressed).
With this behavior every `hold_mode` with `hold_time` has a longer delay as originally (extended by `bouncetime`)

File: components/rfid-reader/RC522/requirements.txt [hunk 2]
```diff
@@ -1,4 +1,8 @@
 # RC522 related requirements
-# You need to install these with `sudo python3 -m pip install --upgrade --force-reinstall -q -r requirements.txt`
+# You need to install these with `sudo python3 -m pip install --upgrade --force-reinstall --no-deps -q -r requirements.txt`
 
+#pi-rc522 has RPi.GPIO as a dependecy which is broken since kernel 6.6.
```
Comment (s-martin) [inline components/rfid-reader/RC522/requirements.txt]:
```suggestion
#pi-rc522 has RPi.GPIO as a dependency which is broken since kernel 6.6.
```

File: scripts/installscripts/install-jukebox.sh [hunk 3]
```diff
@@ -915,6 +919,8 @@ install_main() {
     source "${jukebox_dir}"/scripts/helperscripts/inc.helper.sh
     source "${jukebox_dir}"/scripts/helperscripts/inc.networkHelper.sh
 
+    # Remove exluded libs, if installed - see https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2469
```
Comment (s-martin) [inline scripts/installscripts/install-jukebox.sh]:
```suggestion
    # Remove excluded libs, if installed - see https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2469
```

File: CONTRIBUTING.md [hunk 4]
```diff
@@ -93,6 +93,8 @@ If the code change results in a test failure, we will make our best effort to co
 
 * All code has to run under the stable and legacy version of Raspberry Pi OS (please check if currently even an older version is still supported).
 * For GPIO all code should work with **RPi.GPIO**. gpiozero is currently not intended to use.
+    > [!IMPORTANT]
+    > The original `RPi.GPIO` packages is currently not compatible with the 6.6 kernel (since bookworm). Therefore the lib `rpi-lgpio` is used as a replacement, which is api compliant. `RPi.GPIO` must not be installed directly or as a dependency as this breaks GPIO functionality (see `requirements-excluded`)!
```
Comment (s-martin) [inline CONTRIBUTING.md]:
```suggestion
    > The original `RPi.GPIO` package is currently not compatible with the 6.6 kernel (since bookworm). Therefore the lib `rpi-lgpio` is used as a replacement, which is api compliant. `RPi.GPIO` **must not** be installed directly or as a dependency as this breaks GPIO functionality (see `requirements-excluded`)!
```

File: packages-excluded.txt [hunk 5]
```diff
@@ -0,0 +1,5 @@
+# Remove exluded libs, if installed - see https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2469
```
Comment (s-martin) [inline packages-excluded.txt]:
```suggestion
# Remove excluded libs, if installed - see https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2469
```

File: requirements-excluded.txt [hunk 6]
```diff
@@ -0,0 +1,5 @@
+# Remove exluded libs, if installed - see https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2469
```
Comment (s-martin) [inline requirements-excluded.txt]:
```suggestion
# Remove excluded libs, if installed - see https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2469
```

File: scripts/installscripts/install-jukebox.sh [hunk 7]
```diff
@@ -948,8 +954,8 @@ install_main() {
     echo "${VERSION_NO} - ${COMMIT_NO} - ${USED_BRANCH}" > ${jukebox_dir}/settings/version
     chmod 777 ${jukebox_dir}/settings/version
 
-    # Remove RPi.GPIO, if still installed - see https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/2313
-    sudo python3 -m pip uninstall -y -q rpi-gpio
+    # Remove exluded libs, if installed - see https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2469
```
Comment (s-martin) [inline scripts/installscripts/install-jukebox.sh]:
```suggestion
    # Remove excluded libs, if installed - see https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2469
```

File: scripts/installscripts/install-jukebox.sh [hunk 8]
```diff
@@ -982,9 +988,18 @@ install_main() {
         sudo chmod 440 "${sudoers_mopidy}"
     fi
 
+    # prepare lgpio build for bullseye as the binaries are broken
+    local pip_install_options=""
+    if [ "${OS_VERSION_ID}" -le "11" ]; then
+        ${apt_get} install swig unzip
+        mkdir -p tmp && cd tmp && wget -q http://abyz.me.uk/lg/lg.zip && unzip lg.zip > /dev/null && cd lg && make > /dev/null && sudo make install > /dev/null
```
Comment (s-martin) [inline scripts/installscripts/install-jukebox.sh:995]: Do we need to pin a version here?

Comment (AlvinSchiller) [reply scripts/installscripts/install-jukebox.sh:995]: You mean for lgpio? I didn't find a versioned zip file, only the one with latest and greatest, as described in the installation guide.

**Review by AlvinSchiller — APPROVED** [review]

File: scripts/installscripts/install-jukebox.sh (hunk 8 above)
Comment (s-martin) [reply scripts/installscripts/install-jukebox.sh:995]: Ok, then we keep it that way
