### PR TITLE
Replace RPi.GPIO with rpi-lgpio for V3 future3

### LINKED ISSUE #2313: 🐛 | bookworm/kernel 6.6 GPIO: Failed to add edge detection
### Version

3.5.2

### Branch

future/main

### OS

RPI OS bookworm lite - 32bit

### Pi model

3 B+

### Hardware

- [Suptronics x400](http://www.suptronics.com/xseries/x400.html) Soundcard
- [MFRC522 RFID Reader](https://rpi-jukebox-rfid.readthedocs.io/en/latest/rfid/mfrc522_spi.html)
- GPIO buttons

### What happened?

After a fresh install of RPI OS bookworm lite, 32-bit with latest `future/main`, the GPIO buttons and the RFID reader stopped working (They worked before with the same configuration on an older 2.x installation on RPI OS bullseye).
I saw [this discussion thread](https://github.com/MiczFlor/RPi-Jukebox-RFID/discussions/2295) which confirms this issue, but I wanted to create a dedicated issue for it, to not bloat the discussion topic too much since it covers also other issues of a bookworm/future/main installation. 

I can see this relevant log entry:

```
Exception in thread read_00Thread:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/varac/RPi-Jukebox-RFID/src/jukebox/components/rfid/reader/__init__.py", line 143, in run
    self._reader = self._reader_module.ReaderClass(self._reader_cfg_key)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/varac/RPi-Jukebox-RFID/src/jukebox/components/rfid/hardware/rc522_spi/rc522_spi.py", line 85, in __init__
    self.device = pirc522.RFID(bus=spi_bus,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/varac/RPi-Jukebox-RFID/.venv/lib/python3.11/site-packages/pirc522/rfid.py", line 103, in __init__
    GPIO.add_event_detect(pin_irq, GPIO.FALLING,
RuntimeError: Failed to add edge detection
```

In the discussion [Sharing tips for future3 on bookworm/kernel 6.6 and upstreaming fixes #2295](https://github.com/MiczFlor/RPi-Jukebox-RFID/discussions/2295) @hoffie pointed out possible ways forward but I am missing concrete instructions know how to actually fix this issue on my current installation. Any help welcome, thanks already !

### Logs

[app.log](https://github.com/MiczFlor/RPi-Jukebox-RFID/files/14812716/app.log)
[errors.log](https://github.com/MiczFlor/RPi-Jukebox-RFID/files/14812717/errors.log)
[INSTALL-1710188086.log](https://github.com/MiczFlor/RPi-Jukebox-RFID/files/14812718/INSTALL-1710188086.log)

### Configuration

[rfid.yaml.txt](https://github.com/MiczFlor/RPi-Jukebox-RFID/files/14812730/rfid.yaml.txt)
[jukebox.yaml.txt](https://github.com/MiczFlor/RPi-Jukebox-RFID/files/14812731/jukebox.yaml.txt)
[gpio.yaml.txt](https://github.com/MiczFlor/RPi-Jukebox-RFID/files/14812733/gpio.yaml.txt)

### More info

_No response_

### PR DESCRIPTION
**Pull request by s-martin**
Following the discussion in https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/2313 replacing RPi.GPIO with [rpi-lgpio](https://rpi-lgpio.readthedocs.io/en/latest/index.html)

- [x] Clarify if we need a check mechanism to not accidentally install RPi.GPIO as dependency in the future - see comment from @AlvinSchiller https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2469#issuecomment-2564880847
- [x] Make sure that rc522 does not install RPi.GPIO as dependency (—no-deps) - pointer: https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/0ee5bc3f0da45ad935e7b046c4ce7653c9ed00a6/src/jukebox/components/rfid/configure/__init__.py#L29-L37
- [x] build rpi-lgpio also manually on Bullseye - see #2469 

@hoffie @varac

### CODE REVIEW

**Review by Groovylein — APPROVED** [review]

**Comment by s-martin** [comment]
Anybody using a RC522 reader is welcome to test the change (also #2469 if you use V2) as I don't have a RC522 reader.

**Comment by pabera** [comment]
Is the API interchangeable? It seems easy, but should be tested with some default components

**Review by pabera — COMMENTED** [review]
It's a good idea, but I don't think we need it. Our installation does not qualify for reinstallation anyways. It should not be installed by default.

File: installation/routines/setup_jukebox_core.sh [hunk 1]
```diff
@@ -30,6 +30,8 @@ _jukebox_core_install_python_requirements() {
   source "$VIRTUAL_ENV/bin/activate"
 
   pip install --upgrade pip
+  # Remove RPi.GPIO, if still installed - see https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/2313
```
Comment (pabera) [inline installation/routines/setup_jukebox_core.sh]: It's a good idea, but I don't think we need it. Our installation does not qualify for reinstallation anyways. It should not be installed by default.

**Comment by s-martin** [comment]
> * [ ]  Clarify if we need a check mechanism to not accidentally install RPi.GPIO as dependency in the future - see comment from @AlvinSchiller [Replace RPi.GPIO with rpi-lgpio for V2 legacy #2469 (comment)](https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2469#issuecomment-2564880847)
> 

Just thought about checking the installed package (and making sure RPi.GPIO is not installed) at least in the CI, but I realized that we don’t have these CI checks in future3 yet.

**Comment by s-martin** [comment]
I think for future3 to fix the rc522 issues https://github.com/hoffie/pi-rc522-gpiozero would be a good solution as we use gpiozero anyway in future3.

@pabera @AlvinSchiller

**Comment by s-martin** [comment]
Added task to build rpi-lgpio manually on Bullseye - some users already tried to install on Bullseye (https://github.com/MiczFlor/RPi-Jukebox-RFID/discussions/2481#discussioncomment-11809284)

**Comment by AlvinSchiller** [comment]
- updated rpi-lgpio installation (incl build lgpio for bullseye)
- add installation check that `RPi.GPIO` is not installed (after core dependencies)
- switched `pi-rc522` lib to `pi-rc522-gpiozero` fork from [hoffie](https://github.com/hoffie/pi-rc522-gpiozero)
- removed all direct RPi.GPIO references to be fully gpiozero compatible (e.g. usage of LgpioFactory)
  - formerly rpi specific host functions now check if command is available on system (tvservice for `hdmi_power_down` also not available on bookworm lite).

File: installation/routines/setup_jukebox_core.sh [hunk 2]
```diff
@@ -24,13 +24,33 @@ _jukebox_core_install_os_dependencies() {
...
 
-  cd "${INSTALLATION_PATH}"  || exit_on_error
+  cd "${INSTALLATION_PATH}" || exit_on_error
 
   python3 -m venv $VIRTUAL_ENV
   source "$VIRTUAL_ENV/bin/activate"
 
   pip install --upgrade pip
-  pip install --no-cache-dir -r "${INSTALLATION_PATH}/requirements.txt"
+  # Remove excluded libs, if installed - see - see https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2470
```
Comment (s-martin) [inline installation/routines/setup_jukebox_core.sh]:
```suggestion
  # Remove excluded libs, if installed - see https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2470
```

File: src/cli_client/pbc.c
Comment (s-martin) [inline src/cli_client/pbc.c:1]: The open PR #2452 removes the C tool and we use just the Python tool.

Comment (AlvinSchiller) [reply src/cli_client/pbc.c:1]: Ahhh there it was. I had in mind this changed somehow but didn't find where 😄

I will revert this change to not cause merge conflicts.

File: installation/routines/setup_jukebox_core.sh [hunk 3]
```diff
@@ -24,13 +24,33 @@ _jukebox_core_install_os_dependencies() {
...
+    local lg_filename="lg"
+    local lg_zip_filename="${lg_filename}.zip"
+
+    sudo apt-get -y install swig unzip
+    mkdir -p "${tmp_path}" && cd "${tmp_path}" || exit_on_error
+    wget --quiet http://abyz.me.uk/lg/${lg_zip_filename} || exit_on_error "Download failed"
+    unzip ${lg_zip_filename} || exit_on_error
+    cd "${lg_filename}" || exit_on_error
+    make && sudo make install
+    cd "${INSTALLATION_PATH}" && sudo rm -rf "${tmp_path}"
```
Comment (pabera) [inline installation/routines/setup_jukebox_core.sh]: Consider splitting the lgpio build logic into a separate function for better maintainability

File: requirements-excluded.txt [hunk 4]
```diff
@@ -0,0 +1,5 @@
+# Remove excluded libs, if installed - see https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2470
+# Libraries which must be excluded. These must be removed with
+# You need to uninstall these with `python -m pip uninstall -y -r requirements.txt`
```
Comment (pabera) [inline requirements-excluded.txt]: Good documentation of purpose, but can we add more details about why RPi.GPIO needs to be excluded.

File: src/jukebox/components/rfid/hardware/rc522_spi/rc522_spi.py [hunk 5]
```diff
@@ -87,7 +86,7 @@ def __init__(self, reader_cfg_key):
                                    pin_rst=pin_rst,
                                    pin_irq=pin_irq,
                                    antenna_gain=antenna_gain,
-                                   pin_mode=GPIO.BCM)
+                                   pin_mode='BCM')
```
Comment (pabera) [inline src/jukebox/components/rfid/hardware/rc522_spi/rc522_spi.py:89]: Does this accept strings?

Comment (AlvinSchiller) [reply src/jukebox/components/rfid/hardware/rc522_spi/rc522_spi.py:89]: Yep, [see](https://github.com/hoffie/pi-rc522-gpiozero/blob/1dc878c8a3d6f32ad6601877b00e7316d72811d1/pirc522/rfid.py#L13).
 It would work also with `GPIO.BCM` but i wanted to eliminate the import and give the possibility to use other gpio libs for gpiozero.
